import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import { connectDB } from "@/lib/mongodb";

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  await connectDB();
 
  return (
    <html lang="en">
      <body>
          <Navbar/>
        {children}
      </body>
    </html>
  );
}
